version: '3'

services:
  ssh2iot:
    build:
      context: .
      dockerfile: ./Dockerfiles/ssh2iot.Dockerfile
    image: ssh2iot:latest
    entrypoint: 'true'

  thing_1:
    build:
      context: .
      dockerfile: ./Dockerfiles/thing.Dockerfile
    image: thing:latest
    volumes:
      - ./src:/app
      - ./certs:/certs
      - ./authorized_keys:/root/.ssh/authorized_keys
    environment:
      - CLIENT_ID=MyIotThing1
    env_file:
      - things.env

  thing_2:
    depends_on:
      - thing_1
    image: thing:latest
    volumes:
      - ./src:/app
      - ./certs:/certs
      - ./authorized_keys:/root/.ssh/authorized_keys
    environment:
      - CLIENT_ID=MyIotThing2
    env_file:
      - things.env
